name: "dbt_in_123"
version: "1.0.0"
profile: "dbt_in_123"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_in_123:
    otb:
      +materialized: view
